const CardData = [
    {   
        id: "1",
        title: "Code Optimization",
        description: "Learn techniques to optimize your code for improved performance and efficiency in web applications.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKKpyvG1zKfyYnHmlVtrlBFs0qU_UfwrgbNw&s",
        link: "https://www.youtube.com/watch?v=NWnBxQjssvQ",
    },
    {
        id: "2",
        title: "Front-End Development",
        description: "Explore the latest tools and techniques for creating beautiful and responsive user interfaces.",
        image: "https://www.tatvasoft.com/outsourcing/wp-content/uploads/2023/06/Types-of-Web-Development-for-your-Project-1280x720.jpg",
        link: "https://www.youtube.com/watch?v=fUmSkEvet08&list=PLu0W_9lII9ahwLNzab_rVfZ06ZCZYEcNs",
    },
    {
        id: "3",
        title: "Back-End Development",
        description: "Dive into server-side programming, databases, and APIs to create robust back-end solutions.",
        image: "https://miro.medium.com/v2/resize:fit:1400/1*fHrAZJ1_L0Ff9dvVexL5_A.png",
        link: "https://www.youtube.com/watch?v=KAh2TOrtTq4&list=PLu0W_9lII9ahwLNzab_rVfZ06ZCZYEcNs&index=3",
    },
    {
        id: "4",
        title: "Web Design Principles",
        description: "Understand essential design principles to create visually appealing and user-friendly web pages.",
        image: "https://techbuzz.com.pk/wp-content/uploads/2024/08/what-is-website-development.jpeg",
        link: "https://www.youtube.com/watch?v=OeEHJgzqS1k",
    },
    {
        id: "5",
        title: "JavaScript Essentials",
        description: "Master JavaScript fundamentals to enhance interactivity and functionality on your web pages.",
        image: "https://www.usnews.com/dims4/USNEWS/fb6e5fb/2147483647/crop/2000x1334+0+2/resize/970x647/quality/85/?url=https%3A%2F%2Fwww.usnews.com%2Fcmsmedia%2F65%2F62%2Fc9cb60d24ac89d56462b1228574a%2F201009-codingcomputer-stock.jpg",
        link: "https://youtube.com/watch?v=kRs2PlJByBo&list=PLb6jCeMUfjiHSYHgi7QX1X2MgFNW82ikb",
    },
    {
        id: "6",
        title: "React Basics",
        description: "Get introduced to React, a popular front-end library for building interactive user interfaces.",
        image: "https://www.creative-tim.com/blog/content/images/size/w960/2022/01/which-development-job-is-right-for-you.jpg",
        link: "https://www.youtube.com/watch?v=akUpoNMHMHw&list=PLb6jCeMUfjiHSYHgi7QX1X2MgFNW82ikb&index=10",
    },
    {
        id: "7",
        title: "API Integration",
        description: "Learn how to integrate external APIs into your projects to enhance functionality.",
        image: "https://statics.cdn.200lab.io/2023/08/Thumbnail-blog---Tie-n--3-.png",
        link: "https://www.youtube.com/watch?v=Zjl2vmy02As",
    },
    {
        id: "8",
        title: "Web Development Learning",
        description: "Skilled at troubleshooting and optimizing code, ensuring smooth and efficient website functionality for a seamless user experience.",
        image: "https://edutantr.graphy.com/s/store/courses/65621bcfe4b0657795c8d43b/cover.jpg?v=7",
        link: "https://www.youtube.com/watch?v=akUpoNMHMHw&list=PLb6jCeMUfjiHSYHgi7QX1X2MgFNW82ikb&index=10",
    },
    {
        id: "9",
        title: "Problem Solving",
        description: "Skilled at troubleshooting and optimizing code, ensuring smooth and efficient website functionality for a seamless user experience.",
        image: "https://media.licdn.com/dms/image/v2/D4D12AQE49YY31CtP-Q/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1712688938948?e=2147483647&v=beta&t=h4f7tHrPHMZCcf3GZPL9ZD7VRyMsD1BxboIRn9Ew0uc",
        link: "https://www.youtube.com/watch?v=Zjl2vmy02As",
    },
    {
        id: "10",
        title: "Problem Solving",
        description: "Skilled at troubleshooting and optimizing code, ensuring smooth and efficient website functionality for a seamless user experience.",
        image: "https://media.licdn.com/dms/image/v2/D4D12AQE49YY31CtP-Q/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1712688938948?e=2147483647&v=beta&t=h4f7tHrPHMZCcf3GZPL9ZD7VRyMsD1BxboIRn9Ew0uc",
        link: "https://www.youtube.com/watch?v=Zjl2vmy02As",
    },
    {
        id: "11",
        title: "React Basics",
        description: "Get introduced to React, a popular front-end library for building interactive user interfaces.",
        image: "https://www.creative-tim.com/blog/content/images/size/w960/2022/01/which-development-job-is-right-for-you.jpg",
        link: "https://www.youtube.com/watch?v=akUpoNMHMHw&list=PLb6jCeMUfjiHSYHgi7QX1X2MgFNW82ikb&index=10",
    },
    {   
        id: "12",
        title: "Code Optimization",
        description: "Learn techniques to optimize your code for improved performance and efficiency in web applications.",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKKpyvG1zKfyYnHmlVtrlBFs0qU_UfwrgbNw&s",
        link: "https://www.youtube.com/watch?v=NWnBxQjssvQ",
    },
    {
        id: "13",
        title: "Front-End Development",
        description: "Explore the latest tools and techniques for creating beautiful and responsive user interfaces.",
        image: "https://www.tatvasoft.com/outsourcing/wp-content/uploads/2023/06/Types-of-Web-Development-for-your-Project-1280x720.jpg",
        link: "https://www.youtube.com/watch?v=fUmSkEvet08&list=PLu0W_9lII9ahwLNzab_rVfZ06ZCZYEcNs",
    },
    {
        id: "14",
        title: "Web Development Learning",
        description: "Skilled at troubleshooting and optimizing code, ensuring smooth and efficient website functionality for a seamless user experience.",
        image: "https://edutantr.graphy.com/s/store/courses/65621bcfe4b0657795c8d43b/cover.jpg?v=7",
        link: "https://www.youtube.com/watch?v=akUpoNMHMHw&list=PLb6jCeMUfjiHSYHgi7QX1X2MgFNW82ikb&index=10",
    },
    {
        id: "15",
        title: "Back-End Development",
        description: "Dive into server-side programming, databases, and APIs to create robust back-end solutions.",
        image: "https://miro.medium.com/v2/resize:fit:1400/1*fHrAZJ1_L0Ff9dvVexL5_A.png",
        link: "https://www.youtube.com/watch?v=KAh2TOrtTq4&list=PLu0W_9lII9ahwLNzab_rVfZ06ZCZYEcNs&index=3",
    },
];
export default CardData;